on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # branch testbranch6
        with:
          ref: testbranch8
          fetch-depth: 0

      # Rollback last commit.
      - name: Rollback last commit
        run: |
          git reset --hard HEAD~2
          git push origin HEAD --force