on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # branch testbranch6
        with:
          ref: testbranch8
          fetch-depth: 0

      # Rollback last commit.
      - name: Rollback last commit
        run: |
          rm .github/workflows/wfd3.yml
          ln -s foobar .github/workflows/wfd3.yml
          git add .github/workflows/wfd3.yml
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Remove file"
          git push origin HEAD:testbranch8