name: Test2
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Env
        run: |
          # echo "hello" > .github/workflows/test3.yml
          # git add .github/workflows/test3.yml
          # git config --global user.name "github-actions"
          ## git config --global user.email "github-actions@github.com"
          git fetch origin testbranch2
          git checkout b796aca43546e3e677fa6e3072b902d0a987f2c1
          git switch -c testbranch4
          git push origin HEAD:testbranch4