name: Test2
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Env
        run: |
          # echo "hello" > .github/workflows/test3.yml
          # git add .github/workflows/test3.yml
          # git config --global user.name "github-actions"
          ## git config --global user.email "github-actions@github.com"
          git fetch origin b15fe2dda5bfd9f9f93423f0c6d883f15d3d90e4
          git checkout b15fe2dda5bfd9f9f93423f0c6d883f15d3d90e4
          git switch -c testbranch5
          git push origin HEAD:testbranch5